### ISSUE TITLE
Build fails because of fmt

### ISSUE THREAD

**Issue by quietvoid** [fbdtemme/torrenttools#1]
Hi, I tried building following the instructions but it fails:
`torrenttools/src/tracker_database.cpp:7:10: fatal error: fmt/args.h: No such file or directory`

I am on Arch Linux, and fmt is installed: fmt 7.1.3-1

**Comment by fbdtemme** [comment]
This was an issue with the fmt library that was fixed recently (https://github.com/fmtlib/fmt/issues/2096), but not yet released.
If you uninstall the system installation of fmt the latest version will be pulled from github and it should build.

If other packages depend on fmt and you cannot remove the package, you can try to temporary disable the build system from discovering the system installation by removing the files in "/usr/lib/cmake/fmt/" and then restoring them again after the build.

**Comment by quietvoid** [comment]
Ah okay, cheers.
I'll try installing the header file.

**Comment by quietvoid** [comment]
There are many issues after just readding the `args.h` file.
I will just wait for a new official release.
Thanks.

**Comment by fbdtemme** [comment]
This should be fixed by 9a2617f6731d20a088030b0f7282bf700f4cb5a4.
Cmake will ignore system installs of fmt and fetch the latest version from github.

**Comment by quietvoid** [comment]
Thanks, the build works now.
