### ISSUE TITLE
config.yml mentions Windows and Linux but not macOS

### ISSUE THREAD

**Issue by newadventure079** [fbdtemme/torrenttools#13]
macOS is left out of the following

```
# This is an example configuration file.
# It should be copied to the suitable directory for your OS and modified there.
# Linux : $HOME/.config/torrenttools/config.yml
# Windows : %AppData%/torrenttools/config.yml
```

**Comment by newadventure079** [comment]
`$HOME/Library/Application Support/torrenttools` doesnt exist for me.  I found it in `/Library/torrenttools/etc/`

**Comment by Audionut** [comment]
For Windows it is:

"# Windows : %AppData%\{username}\roaming\torrenttools\config.yml

**Comment by fbdtemme** [comment]
There are two places for configuration: one that is system-wide were the default configuration is stored, and one that is specific for the current user. 
 
On mac the system location is: `/Library/torrenttools/etc/`
and the user location: `$HOME/Library/Application Support/torrenttools/`

On windows the system location is inside the install location: `C:\Program Files\torrenttools\`
and the user location is in: `%APPDATA%\torrenttools`
The default value for `%APPDATA%` can differ a bit between windows versions but on windows 10 this points to:
`C:\Users\{username}\AppData\Roaming`

on linux the system configuration is stored in `/etc`
and the user location `$HOME/.local/torrenttools`

If there are files found in the user location these will be used. 
Only if there is no user configuration, the files in the system location will be used.

@newadventure079 That the directory does not exist is a small difference between the windows installers and the mac installer.
I forgot to create that directory in the mac installer.

I need to add a section about all this in the documentation.

**Comment by btTeddy** [comment]
What about docker?
Where exactly config should exists?

`    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
`
