### ISSUE TITLE
Unknown parsing error on Win10

### ISSUE THREAD

**Issue by Audionut** [fbdtemme/torrenttools#16]
Hi,

Regardless of whether I use the default config.yml, or some configured one, I am getting this error.

`Error: [json.exception.parse_error.101] parse error at line 10, column 15: syntax error while parsing object - unexpected string literal; expected '}'`

If I edit line 10 of the config.yml to enclose the {pid}, like so 
`    pid: {example_pid}`

Then I receive this error.
`Error: yaml-cpp: error at line 10, column 10: bad conversion`

**Comment by fbdtemme** [comment]
You have a missing comma causing a syntax error  in your trackers.json file. Check the review of your pull request to fix it.
The pid should not be enclosed in curly brackets. If you do that you will get a syntax error in your config.yml as well.

**Comment by Audionut** [comment]
Fixed with proper formatting.
