### ISSUE TITLE
Windows 10 stats overwritten

### ISSUE THREAD

**Issue by Audionut** [fbdtemme/torrenttools#18]
https://ptpimg.me/k07nar.png

**Comment by fbdtemme** [comment]
Torrenttools uses ANSI codes and windows cmd.exe and powershell only have limited support for those.
Try the new windows terminal: https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab
Everything should render correctly with the new terminal app.

**Comment by Audionut** [comment]
That terminal is significantly better. Cheers for the heads up.
