### ISSUE TITLE
source tag isnt getting added

### ISSUE THREAD

**Issue by skydrome** [fbdtemme/torrenttools#2]
https://github.com/fbdtemme/torrenttools/blob/main/src/create.cpp#L392
is that a typo?

Using:
```
--comment "this is a comment"  \
--source "testsource" 
```

Ouput:
```
Source:           
Comment:          this is a comment
```

Using only:
```--source "testsource" ```

Ouput:
```
Source:           
Comment:          this is a comment
```

**Comment by fbdtemme** [comment]
Should be fixed now. Thanks for reporting!

**Comment by skydrome** [comment]
Thanks! That did the trick, its working for me now
