### ISSUE TITLE
wrong infohash

### ISSUE THREAD

**Issue by yandrey0** [fbdtemme/torrenttools#22]
[[snk-tv.pro].t150.torrent](https://yandrey.ru/tmp/[snk-tv.pro].t150.torrent)
torrenttools-0.6.0-1.fc33.x86_64.rpm

> _torrenttools info_ \[snk-tv.pro\].t150.torrent 
> Metafile:          /var/data/Upload/[snk-tv.pro].t150.torrent
> Protocol version:  v1
> Infohash:          **14570758501b25e736a1b29ad8b08dfbeb16fe5c**
> Piece size:        1 MiB (1048576 bytes)
> Piece count:       802
> Created by:        uTorrent/3.4.5
> Created on:        2021-08-05 15:16:48 UTC
> Private:           false
> Name:              King Gary s2 1080p SNK-TV
> ...

> _transmission-show_ \[snk-tv.pro\].t150.torrent 
> Name: King Gary s2 1080p SNK-TV
> File: [snk-tv.pro].t150.torrent
> 
> GENERAL
> 
>   Name: King Gary s2 1080p SNK-TV
>   Hash: **79cdf0937d3a6e35200aac218a36a6abb8e4fa33**
>   Created by: uTorrent/3.4.5
>   Created on: Thu Aug  5 22:16:48 2021
>   Comment: http://snk-tv.pro/viewtopic.php?t=150
>   Piece Count: 802
>   Piece Size: 1.00 MiB
>   Total Size: 840.0 MB
>   Privacy: Public torrent
> ...

**Comment by fbdtemme** [comment]
Fixed in v0.6.1.
Thanks for reporting!
