### ISSUE TITLE
Single Announce URL not getting added

### ISSUE THREAD

**Issue by SpookyStuff** [fbdtemme/torrenttools#3]
Using: 
`torrenttools create -a "https://blah1.com" -p -l 21 -v '1' -o ~/somewhere/ ~/somewhere/something`

Results in no announce URL being added to the metafile

**Announces:**

----------------------------
Using:
`torrenttools create -a "https://blah1.com" "https://blah2.com" -p -l 21 -v '1' -o ~/somewhere/ ~/somewhere/something`

Results in both URLs being added to the metafile

**Announces:
tier 1  - https://blah1.com
tier 2  - https://blah2.com**

**Comment by fbdtemme** [comment]
This was fixed in 9f79c3950065ab3e5b7cab0f0067777d5bfd5c05 but was not released until now with the v0.3.0 release.

**Comment by SpookyStuff** [comment]
Cool. I can see while processing that it picks up the single announce URL. But, now in 0.30, seems like after it completes, there is no metafile written where it says it was written

**Comment by fbdtemme** [comment]
The output option should be fixed in 9c00e2f.
Thanks for reporting! Keep it up :slightly_smiling_face:
