### ISSUE TITLE
how to double-check verify?

### ISSUE THREAD

**Issue by diligiant** [fbdtemme/torrenttools#42]
I'm having a problem verifying some large torrents that a (doubled, tripled) verified by transmission but have either their unique large file or the last of their files listed as 99% by torrenttools.

I was wondering if I had a way to get detailed output and/or instructions to debug this ?

[I then picked torf (from your performance chart) and verified one torrent. It agrees with transmission so I'm inclined to think I found a bug. How can I help?]

**Comment by fbdtemme** [comment]
Hi, 

Thanks for reporting this.

You can show detailed information about each piece in your torrent file with this command.
```
torrenttools info  --show-pieces --raw "your-file.torrent" > torrent-data.json
```
:warning: Please redact filenames and or passkeys in the resulting JSON document if needed.

Then create a new .torrent file with torrenttools using the same piece size as the original torrent from your data. 
You can then run the same `torrentools info` command as above on this new .torrent.

If you send me these two JSON files I can look into which piece is getting miscalculated.
It would also be useful to load this newly created .torrent in transmission and see if it verifies to 100%.

**Comment by diligiant** [comment]
My bad, it's not a bug (sorry): There is sometimes junk in torrents so I remove them. Something junk is in the same piece as an interesting file so verify is missing data to correctly match the sha1. It's not that the file is bad but verify "doesn't know". (I thought each file was independent…)

May I suggest that you report the inability to verify properly first/last byes of the file as "file(s) XZY" before/after is/are missing. This would be much less frightening ;)

Sorry again.

**Comment by fbdtemme** [comment]
No problem,
Extending verify to warn the user when a file before/after is missing, (and causing the the file that is complete to not check completely to 100%) is a good suggestion.
