### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by RemuxKid** [fbdtemme/torrenttools#5]
Hey! The project looked extremely promising so I had to give it a go. Unfortunately I have run into an error on my first torrent creator.

`torrenttools create "E:\Docker\Deluge\Data\linux.iso"  --piece-size 4M --announce "XXX" -p on -o "E:\Docker\Deluge\Data\linux.torrent"`

  16.00 EiB in 0 directories, 1 files

Error: std::bad_alloc

**Comment by fbdtemme** [comment]
The reported file size looks weird: 16.00 EiB. What is the filesize of the target you are trying to create a torrent from?

**Comment by RemuxKid** [comment]
> The reported file size looks weird: 16.00 EiB. What is the filesize of the target you are trying to create a torrent from?

About 27GB

**Comment by RemuxKid** [comment]
Even with a different file, it's thinking it's 16 EiB

**Comment by fbdtemme** [comment]
I think something goes wrong while retrieving information of the target from the filesystem on windows. I am trying to reproduce the issue now.

**Comment by fbdtemme** [comment]
Sadly I currently don't have the time to support the windows version.
I have dropped windows support in the latest release.
I plan to make torrenttools available on windows again sometime in the future.
If you still want to use torrenttools on windows you can try out the docker container for now.
