### ISSUE TITLE
Publishing an official Docker image?

### ISSUE THREAD

**Issue by past-due** [fbdtemme/torrenttools#6]
Thanks for what looks to be a fantastic tool.

There are some cases where having a Docker image to easily run `torrenttools` might be more convenient / desirable than the existing COPR / launchpad repos.

Would you be willing to consider publishing an official Docker image that is updated as part of releases?

**Comment by fbdtemme** [comment]
This is certainly a good idea. I will create an image when I have some time.

**Comment by fbdtemme** [comment]
There is now a docker image available on [docker hub](https://hub.docker.com/repository/docker/fbdtemme/torrenttools).
