### ISSUE TITLE
Extract the SHA-1 hashes from the torrent and write them into a sha1sum file.

### ISSUE THREAD

**Issue by minhngoc25a** [fbdtemme/torrenttools#7]
This is related to [this comment in a Reddit post](https://www.reddit.com/r/torrents/comments/mlmigw/can_i_create_a_sfv_file_from_a_torrent_file/gtnbet8?utm_source=share&utm_medium=web2x&context=3).

**Comment by fbdtemme** [comment]
As mentioned in the reddit post there is no way to extract the checksums suitable for checksum files such as .sha1sum without the suitable data being added during torrent creation. Right now it is possible to embed that data with the "--checksum" options but there is no option yet to extract that data so I will add an option to extract checksum data from the torrent if available.

**Comment by fbdtemme** [comment]
Now available in the 0.5.0 release
